import '@/styles/globals.css'
import type { Metadata } from 'next'
import type { ReactNode } from 'react'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang='en'>
      <body suppressHydrationWarning>
        <main className='container mx-auto h-screen min-h-[48rem] border border-primary'>{children}</main>
      </body>
    </html>
  )
}
